### ISSUE TITLE
How to send Client Side HTTP Headers

### ISSUE THREAD

**Issue by Ritvik-UX** [stevepryde/thirtyfour#147]
Is it possible to send Custom HTTP Request Headers from ThirtyFour?

**Comment by stevepryde** [comment]
Could you please elaborate on what you're trying to do?

This crate works by sending requests to a webdriver-compatible REST server, which in turn controls a browser. I'm not sure what value there would be in sending custom HTTP request headers to the webdriver server.

However, maybe you mean adding custom HTTP request headers to requests made from the browser by your web app? I don't think that's possible, because those requests are controlled by your app. Perhaps you could do some kind of proxying using Chrome Devtools Protocol (CDP). Selenium 4.x does allow you to intercept network requests (although official support for that is not yet in thirtyfour) so that might be a possibility. Thirtyfour does support CDP at a low level so if you know how to construct the CDP request etc you can extend thirtyfour to do it.

Start here:
https://docs.rs/thirtyfour/latest/thirtyfour/extensions/cdp/struct.ChromeDevTools.html

CDP docs are here:
https://chromedevtools.github.io/devtools-protocol/

**Comment by Ritvik-UX** [comment]
Wow! Thanks 😃
Amazing crate!
