### ISSUE TITLE
wait until element to disappear

### ISSUE THREAD

**Issue by Daniel-Xu** [stevepryde/thirtyfour#187]
My flow is:
1. signup page, there's a signup button, I will click this button 
```
        let elem_submit: WebElement = driver.find(By::Css("button[type='submit']")).await?;
        elem_submit.click().await?;
```
2. after clicking the button, the signup process is finished and the page will be redirected to login page. However, there's a login button which is exactly the same in terms of css selector (the text is different)
3. when I do this:
```
elem_submit.wait_until().not_displayed().await?;
```

I always got timeout. can I regard the two buttons the same in selenium?

**Comment by Daniel-Xu** [comment]
Second question:

for a simple html snippet: 
![2023-12-02 at 21 10](https://github.com/stevepryde/thirtyfour/assets/548144/6c58ffff-73bd-425a-ab32-234293d99ca0)

after getting the error element:
```
let elem_error = driver.find(By::Id("errorContainer")).await?;
```

I can't get the textContent by using `elem_error.text().await?`
the child elements are not included in the search result?

**Comment by Daniel-Xu** [comment]
is there a Css select reference?
`"#errorContainer  div"` this css selector doesn't work, the error message is: 
`run should be ok: no such element: CSS(#errorContainer  div)`

**Comment by stevepryde** [comment]
If you want the html rather than the visible text, you should use the `inner_html()` method
https://docs.rs/thirtyfour/latest/thirtyfour/struct.WebElement.html#method.inner_html

**Comment by stevepryde** [comment]
Regarding your login button question, once you have selected an element, any operations on that element will always refer to that specific element. It won't do the "find" again. However, when you initially get the element via "find()", make sure you're getting the right one. It will always give you the first one it finds, searching from the top of the html.

Have a look at xpath selectors for more control over it

**Comment by Daniel-Xu** [comment]
> Regarding your login button question, once you have selected an element, any operations on that element will always refer to that specific element. It won't do the "find" again. However, when you initially get the element via "find()", make sure you're getting the right one. It will always give you the first one it finds, searching from the top of the html.
> 
> Have a look at xpath selectors for more control over it

if I need to find the element again, how can I make sure that the page is finishing reloading? (from signup -> login)

**Comment by stevepryde** [comment]
Waiting for the page to finish loading can be complicated. There is no magic solution because there is no clear definition of when a page has "finished loading".

I highly recommend thinking in terms of what a human would do, and emulating that. If it's difficult to emulate it, then it's a strong indication that your page UX is a little unclear even for a human.

In this case, consider waiting for the button to be displayed with the relevant text. Use the driver.query(..) method for this.
https://docs.rs/thirtyfour/latest/thirtyfour/extensions/query/struct.ElementQuery.html.

This will poll for an element with the given selector. You can use xpath to match the button text within the selector.

This crate is just a selenium/webdriver client so it can do anything selenium/webdriver can do. For general selenium or webdriver questions like this I'd recommend searching the selenium documentation or other webdriver related forums for answers.
