### ISSUE TITLE
[Feature request] find_elements() that doesn't wait.

### ISSUE THREAD

**Issue by audioXD** [stevepryde/thirtyfour#31]
I wanted to migrate my `fantoccini` project to `thirtyfour` since it had find_element timeouts. But when was trying to migrate I realized that I need a method that doesn't wait for the element and returns the  current element even if it doesn't exist/hasn't loaded. I know I can set the timeout but it became annoying when i had to set the timeout to 0 and then reset it back. And bacause i didn't always have a handle to `WebDriver`. 

# What I want:
 - A version of `find_element()` and `find_elements()` that doesn't wait and returns the current state (AKA error that no element was found).
 - If possible I would like to get a reference to the element if not a simple boolean would suffice.

# Why:
 - I need to know if a element exists and/or is loaded.

# How I would implement it:
 - The optimal thing would be to have a `wait_find_element() `and `find_element()` but that would *break code compatibility*,
 - Have an argument defining the timeout
 - Have a `element_exist()` method, or with a different name like `has_element()`,` is_present()`, that returns a bool
 - Have a `find_optional_element()` that returns a Option<Element>
 - Have a`find_present_element()` that returns a Result<Element>.

**NOTE** OF course all of them would be wrapped with a WebdriverResult.

Please if you could find a solution because this is the only problem stopping me from migration.

**Comment by audioXD** [comment]
Duplicate requirest #24

**Comment by audioXD** [comment]
After reading i realized that this(#24) issue only intends to add methods to WebElement.

**Comment by stevepryde** [comment]
Have a look at [thirtyfour_query](https://github.com/stevepryde/thirtyfour_query) and let me know if that is a better fit for what you need. It would be trivial to add an `exists()` method there as well.

Eventually I think that will become part of `thirtyfour` but I started it as a separate crate in order to experiment with it while I sort out the interface.

Unfortunately the WebDriver W3C spec provides no way to specify whether or not to implicitly wait as an option for each element find request, so it's only a global setting that is either on or off. Because of that, I prefer to turn it off and use an interface like `thirtyfour_query` to poll. This also gives greater power over the exact polling semantics as well.

**Comment by fapingalot** [comment]
Thank you so I just do: 
 - `driver.query(By:Css(/* my selector*/)).first().await` to get a Result
 - `driver.query(By:Css(/* my selector*/)).exists().await` to return a bool

**Comment by audioXD** [comment]
Thank you so I just do: 
 - `driver.query(/* my selector*/).first().await` to get a Result
 - `driver.query(/* my selector*/).exists().await` to return a bool

**Comment by stevepryde** [comment]
Yes that should do it. 👍
