### ISSUE TITLE
Is there any "Selector"?

### ISSUE THREAD

**Issue by eucylin** [stevepryde/thirtyfour#36]
Hi, I want to select a drop-down item in the selector.
In Selenium with Python, I can do it by : 

```
from selenium.webdriver.support.ui import Select

s1 = Select(driver.find_element_by_id('s1Id'))

s1.select_by_index(1)
s1.select_by_value("o2") 
s1.select_by_visible_text("o3") 
```

Is there any equivalent to do these things in ThirtyFour?

**Comment by stevepryde** [comment]
The `Select` class in the python library is just a convenient wrapper around existing functionality. It uses WebElement.find_elements() to find any descendants with the "option" tag and then essentially applies a predicate to these options to figure out which one to click.

Thus far I've avoided adding a similar wrapper because:
(a) actual `<select>` elements are far less common these days (modern frameworks like bootstrap and material-ui code do dropdowns differently), and
(b) the python implementation actually doesn't open the dropdown (it "clicks" the option element directly) which might be undesirable if you're aiming to mimic what a user might do. For multi-select there is no "dropdown" so it's fine in that case.

To implement this yourself all you need to do is something like this (using your code as an example):
```rust
let elem = driver.find_element(By::Id("s1Id")).await?;
// Then one of the following depending on which type of search you want.

// By index.
elem.find_elements(By::Tag("option")).await?[1].click().await?;
// By value.
elem.find_element(By::XPath("option[@value='o2']")).await?.click().await?;
// By visible text - the python one is more complicated but I'm not sure you need it
elem.find_element(By::XPath("option[contains(text(), 'o3')]")).await?.click().await?;
```

I haven't tested this but some variant of it should work. Obviously the python implementation covers multi-select lists as well.
In the meantime I will leave this issue open and look at adding an official wrapper similar to the python one sometime.

**Comment by stevepryde** [comment]
I've added `SelectElement` in v0.22.2, which is a fairly direct port of the `Select` class from the python selenium library.

**Comment by eucylin** [comment]
Ah, that makes sense! I tried the method you provided and it worked well as expected.
I'll also try the new Select class sometime.
Really appreciate your quick response. 😄
