### ISSUE TITLE
What are the default durations for the WebDriver::Query timeout and polling / What is a reasonable polling time

### ISSUE THREAD

**Issue by bcpeinhardt** [stevepryde/thirtyfour#66]
What are the default durations for the WebDriver::Query timeout and polling? I'm working with a website with slow load times and I'd like to increase the explicit wait timeout. I know I can set this with .wait() on the query but I'm not sure what a reasonable default for the poll time is, as I've never had a need to manually set it before.

**Comment by stevepryde** [comment]
The default timeout is 20 seconds and the default interval is 0.5 seconds. These should be reasonable but you can create and set a different default poller by using the set_poller() method.

The reason this is better than using implicit waits is because your code now has the option to not wait if you just want to check whether something exists without blocking.

When trying to decide on a reasonable default timeout, consider how long you would normally need to wait for a page to load or an element to show up before you would consider it a bug. This is obviously in the context of testing websites. If you're just automating a website you may have different considerations.

**Comment by bcpeinhardt** [comment]
Thanks! Yup I'm actually automating a site for use (its an order management system where we process orders) not testing so generally the consideration for an element that's supposed to be there is how long until I'm pretty damn sure there has been an error. For an element that may or may not be there where I need to make a decision based on whether or not it is present, I try to explicit wait on some indicator element that is always there (like a div container the element is in etc) that will let me know the element would be loaded if it were supposed to be, then do a nowait query on the element I'm looking for, otherwise the explicit waits will build up fast. As I'm adding functionality I'm moving away from page objects and toward component objects now so this will likely get built into those. I had to build the MVP in JavaScript with the npm selenium-webdriver but now I'm porting to Rust and pretty pumped to see how much I can clean up this code with your query api, and also just to be in rust again in general.

**Comment by stevepryde** [comment]
Also note that if the element is found then it will return immediately. The wait / timeout only applies in the case where the element query couldn't find the element.

Have a look through the query interface for more details.

Also if you have an existing element already and want to wait for it to either change an attribute or disappear you can use the element.wait() features for that.
