### ISSUE TITLE
Multiple WebDrivers One Window

### ISSUE THREAD

**Issue by bcpeinhardt** [stevepryde/thirtyfour#68]
I'm working on a project where I manage between 3 and 7 WebDrivers at any given time. They are really cluttering up my desktop while they're running. Is the a way to run multiple unique WebDrivers in the same window just on different tabs?

**Comment by stevepryde** [comment]
Not as far as I am aware, sorry.

However if you are having trouble with too many windows on the screen, perhaps you can either try headless mode or otherwise run one of the selenium docker containers. These will launch the browsers in an xvfb session and you can view them with a vnc viewer.

https://github.com/SeleniumHQ/docker-selenium

**Comment by bcpeinhardt** [comment]
Thanks!
